# Arrays

In [81]:
a = input()
b = map(int,input().split())
print(sum(b))

6
1 2 3 4 10 11
31


# Shape and Reshape

In [79]:
import numpy
print(numpy.array(input().split(), int).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten

In [78]:
import numpy
a, b = map(int, input().split())
c = numpy.array([input().strip().split() for _ in range(a)], int)
print (c.transpose())
print (c.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Concatenate

In [72]:
import numpy
a, b, c = map(int,input().split())
A = numpy.array([input().split() for _ in range(a)],int)
B = numpy.array([input().split() for _ in range(b)],int)
print(numpy.concatenate((A, B), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Zeros and Ones

In [71]:
import numpy as np
shape= tuple(map(int,input().split()))
print(np.zeros(shape,int), np.ones(shape,int), sep='\n')

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and Identity

In [65]:
import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array Mathematics

In [64]:
import numpy
n,m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
print(a+b,a-b,a*b,a//b,a%b,a**b,sep="\n")

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Floor, Ceil and Rint

In [63]:
import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Sum and Prod

In [62]:
import numpy
a, b = map(int, input().split())
c = numpy.array([input().split() for _ in range(a)], int)
print(numpy.prod(numpy.sum(c, axis=0), axis=0))

2 2
1 2
3 4
24


# Min and Max

In [88]:
import numpy as np
a, b = map(int, input().split())
print(np.array([input().split() for _ in range(int(a))], int).min(1).max())

4 2
2 5
3 7
1 3
4 0
3


# Mean, Var, and Std

In [87]:
import numpy as np
a, b = map(int, input().split())
c = np.array([input().split() for _ in range(a)],dtype = int)
np.set_printoptions(legacy='1.13')
print(np.mean(c,axis=1), np.var(c,axis=0), np.std(c), sep='\n')

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Dot and Cross

In [86]:
import numpy as np

c = int(input())
a = np.array([input().split() for _ in range(c)], int)
b = np.array([input().split() for _ in range(c)], int)
print(np.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Inner and Outer

In [85]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


# Polynomials

In [83]:
import numpy as np

a = [float(x) for x in input().split()]
b = float(input())
print(np.polyval(a, b))

1.1 2 3
0
3.0


# Linear Algebra

In [82]:
import numpy as np

np.set_printoptions(legacy='1.13')

a = int(input())
b = np.array([input().split() for _ in range(a)], float)
print(np.linalg.det(b))

2
1.1 1.1
1.1 1.1
0.0
